# Generated by Django 5.2.7 on 2025-10-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={'permissions': [('puede_editar', 'Puede editar estudiantes'), ('puede_eliminar', 'Puede eliminar estudiantes')]},
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nota1',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nota2',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nota3',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='promedio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
